export enum EnumActions {
    eAction_OpenHome = 'eAction_ViewHome',
    eAction_OpenArticles = 'eAction_OpenArticles',
    eAction_OpenEntities = 'eAction_OpenEntities',
    eAction_OpenUsers = 'eAction_OpenUsers',
    eAction_OpenUserRoles = 'eAction_OpenUserRoles',
    eAction_OpenQuotes = 'eAction_OpenQuotes',
    eAction_OpenDocuments = 'eAction_OpenDocuments',
    eAction_OpenInvoices = 'eAction_OpenInvoices',
    eAction_OpenCustomers = 'eAction_OpenCustomers',
    eAction_OpenPersons = 'eAction_OpenPersons',
    eAction_OpenConfig = 'eAction_OpenConfig',
    
    eAction_New = 'eAction_New',
    eAction_Edit = 'eAction_Edit',
    eAction_Delete = 'eAction_Delete',
    eAction_View = 'eAction_View',
    eAction_Save = 'eAction_Save',
    eAction_Cancel = 'eAction_Cancel',
    eAction_Search = 'eAction_Search',
    eAction_Export = 'eAction_Export',
    eAction_Print = 'eAction_Print',
    eAction_Close = 'eAction_Close',
    eAction_List = 'eAction_List',
    eAction_Open = 'eAction_Open',
    eAction_Apply = 'eAction_Apply',
    eAction_Reset = 'eAction_Reset',
    eAction_Accept = 'eAction_Accept',
    eAction_Logout = 'eAction_Logout',
    eAction_Login = 'eAction_Login',


    // actionView = 'visibility',
    // actionSave = 'save',
    // actionCancel = 'cancel',
    // actionSearch = 'search',
    // actionExport = 'export',
    // actionPrint = 'print',
    // actionClose = 'close',
    // actionList = 'list',
    // actionOpen = 'open',
    // actionApply = 'apply',
    // actionReset = 'reset',
    // actionAccept = 'accept',
    // actionLogout = 'exit_to_app',
    // actionLogin = 'login',


}